/*
 * $Id$
 * Copyright 2000,2005 j-wingS development team.
 *
 * This file is part of j-wingS (http://www.j-wings.org).
 *
 * j-wingS is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * Please see COPYING for the complete licence.
 */
package wingset;


import org.wings.*;
import org.wings.event.SComponentAdapter;
import org.wings.event.SComponentEvent;
import org.wings.session.SessionManager;

/**
 * A basic WingSet Pane, which implements some often needed functions.
 *
 * @author <a href="mailto:haaf@mercatis.de">Armin Haaf</a>
 * @version $Revision$
 */
abstract public class WingSetPane
        extends SPanel
        implements SConstants {

    private static final SResourceIcon SOURCE_LABEL_ICON =
            new SResourceIcon("org/wings/icons/File.gif");

    private boolean initialized = false;

    public WingSetPane() {
        setLayout(createResourceTemplate("/templates/ContentLayout.thtml"));

        SAnchor anchor = new SAnchor("/wingset/" +
                getClass().getName().substring(getClass().getName().indexOf('.') + 1) + ".java");
        anchor.setTarget("sourceWindow");
        anchor.add(new SLabel("view source code", SOURCE_LABEL_ICON));
        add(anchor, "viewSource");

        addComponentListener(new SComponentAdapter() {
            public void componentShown(SComponentEvent e) {
                if (!initialized) {
                    add(createExample(), "content"); // content generated by example
                    initialized = true;
                }
            }
        });
    }

    /**
     * Override this.
     */
    protected abstract SComponent createExample();

    protected static SLayoutManager createResourceTemplate(String name) {
        try {
            return new STemplateLayout(SessionManager.getSession().getServletContext().getRealPath(name));
        } catch (Exception except) {
            except.printStackTrace();
        }
        return null;
    }
}
