#
# $Id$
#
# see Rules.make
##

fun: 

% :
	make -C org/wings $@
	make -C org/wings/io $@
	make -C org/wings/util $@
	make -C org/wings/externalizer $@
	make -C org/wings/servlet $@
	make -C org/wings/session $@
	make -C org/wings/plaf $@
	make -C org/wings/plaf/xhtml $@
	make -C org/wings/plaf/xhtml/css1 $@
	make -C org/wings/template $@
	make -C org/wings/date $@

