#
# $Id$
#
# see Rules.make
##

% :
	make -C io $@
	make -C util $@
	make -C externalizer $@
	make -C servlet $@
	make -C session $@
	make -C plaf $@
	make -C template $@
	make -C date $@

include ${DEVEL_HOME}/Rules.make

