/*
 * $Id$
 * Copyright 2000,2005 wingS development team.
 *
 * This file is part of wingS (http://www.j-wings.org).
 *
 * wingS is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * Please see COPYING for the complete licence.
 */
package org.wings.event;

import org.wings.SComponent;

/**
 * The Listener interface for receiving drop events generated by the drag and
 * drop API.
 * @author ole
 */
public interface SComponentDropListener {
    /**
     * Invoked when a component has been dropped onto the component we're
     * listening on.
     * @param dragSource the dropped component
     * @return If the event was handled by this.
     */
    boolean handleDrop(SComponent dragSource);
}
